---
title: "Bimomial test"
---

# Binomial test

## R

### Exact binomial test
```{r}
n_resp = 50
n_all = 100
p0 = 0.1
alpha = 0.05

out <- binom.test(n_resp, n_all, p = p0,
             alternative = "greater",
             conf.level = 1-alpha)

out
```

## SAS

### Exact binomial test

```
%let p0 = 0.1;

proc freq data=response; 
	tables OUTCOME / nocum norow binomial(sup p=&p0 margin=1E-99);
	by GROUP;
	exact binomial;
run;
```

# Confidence intervals for proportions

## SAS

### Clopper-Pearson

```
%let a0 = 0.05;

proc freq data=response;
   by GROUP TREATMENT;
   tables OUTCOME / binomial(cl=CLOPPERPEARSON) alpha=$a0;
   exact binomial;
run;
```

### Santner-Snell

Haven't found a way of calculating these in R
```
proc freq data = response order = data;
	by GROUP;
	weight N;
	tables TREATMENT*OUTCOME / riskdiff;
	exact riskdiff(method = NOSCORE);
run;
```

# Template below

------------------------------------------------------------------------

## Available R packages

**Optional** If there is only one available package this can be deleted. Otherwise please make a short list, paragraph or table. If there is a reason to use one package vs another please include it. Please make sure to include what version of the packages you are using

## Data used

Just a sentence or two about the data. Consider using a package like {skimr} to help illustrate the data.

## Example Code

### Example using {package name}

**Optional** if there is more than one package

## Comparison

If you are comparing more than one package or between different languages, consider adding in a table to illustrate some of the differences. When comparing between languages it can be nice to have a table with links to the pages with deeper dive of each language for a given method method like this table from the ANCOVA page:

| Analysis                                      | Supported in R          | Supported in SAS          | Results Match | Notes                                                                                    |
|------------|------------|------------|------------|-------------------------|
| ANCOVA using general linear model and lsmeans | [Yes](../R/ancova.html) | [Yes](../SAS/ancova.html) | [Yes](#comp)  | `GLM()` function from **sasLM** with `EMEANS=TRUE` is the easiest to use and matches SAS |

But, even if you are just comparing the difference in same language it can be helpful to have a table with values of interest across different packages. Using dynamic content you can add the values to a table without manually putting in each value

## Conclusion

**Optional** add a conclusion

## Reference

**Optional** add any references you used
